name: Deploy to Arvan Server Ahrom Website

on:
  push:
    branches:
      - main

env:
  SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  SERVER_IP: ${{ secrets.SERVER_IP }}
  USER: ${{ secrets.USER }}
  PROJECT_DIR: ${{ secrets.DIR }}

jobs:
  deploy:
    if: contains(github.event.head_commit.message, '--deploy')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Execute Commands
        uses: appleboy/ssh-action@v1.0.2
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            COMMIT_MESSAGE="${{ github.event.head_commit.message }}"
            PROJECT_DIR=${{ secrets.DIR }}

            cd $PROJECT_DIR
            git checkout main
            git pull
            sudo docker-compose up -d --build

            if [[ $COMMIT_MESSAGE == *"--execute-command="* ]]; then
              COMMAND=$(echo "$COMMIT_MESSAGE" | sed -n 's/.*--execute-command=\(.*\)$/\1/p')
              if [ ! -z "$COMMAND" ]; then
                  echo "Executing command: $COMMAND"
                  sudo docker exec ahrom-website-nextjs bash -c "$COMMAND"
              else
                  echo "No command found to execute."
              fi
            fi